name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22 # ou 20 selon ton besoin
          cache: 'yarn'

      - name: Enable Corepack and set Yarn 4
        run: |
          corepack enable
          corepack prepare yarn@4.0.1 --activate

      - name: Install dependencies
        run: yarn install

      - name: Run ESLint
        run: yarn lint

      - name: Type check
        run: yarn typecheck

      - name: Run tests
        run: yarn test
