name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18 # ou 20 selon ce que tu veux
          # ATTENTION : ne pas activer 'cache: yarn' ici si tu utilises Yarn 4 via Corepack

      - name: Enable Corepack and use Yarn 4
        run: |
          corepack enable
          corepack prepare yarn@4.0.1 --activate

      - name: Check Yarn version
        run: yarn --version

      - name: Install dependencies with Yarn 4
        run: yarn install --immutable

      - name: Run ESLint
        run: yarn lint

      - name: Type check
        run: yarn typecheck

      - name: Run unit tests
        run: yarn test
